import { useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useWard } from "@/lib/ward-store";
import type { AlertStatus } from "@/lib/ward-data";

const filters: ("All" | AlertStatus)[] = ["All", "Open", "Acknowledged", "Resolved"];

export default function AlertsScreen() {
  const colors = useColors();
  const { alerts, patients, acknowledgeAlert, resolveAlert } = useWard();
  const [filter, setFilter] = useState<(typeof filters)[number]>("All");
  const visible = useMemo(() => alerts.filter((alert) => filter === "All" || alert.status === filter).sort((a, b) => Number(b.severity === "Critical") - Number(a.severity === "Critical")), [alerts, filter]);
  const confirmAction = (alertId: string, action: "acknowledge" | "resolve", title: string) => Alert.alert(title, "This changes the local workflow state for this alert.", [{ text: "Cancel", style: "cancel" }, { text: action === "resolve" ? "Resolve" : "Acknowledge", style: action === "resolve" ? "destructive" : "default", onPress: () => action === "resolve" ? resolveAlert(alertId) : acknowledgeAlert(alertId) }]);

  return <ScreenContainer className="px-5"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Text style={[styles.eyebrow, { color: colors.muted }]}>ATTENTION QUEUE</Text><Text style={[styles.title, { color: colors.foreground }]}>Alerts</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Review the latest ward signals in one place.</Text>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filters.map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={({ pressed }) => [styles.filter, { backgroundColor: filter === item ? colors.primary : colors.surface, borderColor: filter === item ? colors.primary : colors.border }, pressed && styles.pressed]}><Text style={{ color: filter === item ? "#FFFFFF" : colors.muted, fontWeight: "700", fontSize: 12 }}>{item}</Text></Pressable>)}</ScrollView>
    <View style={styles.list}>{visible.map((alert) => { const patient = patients.find((item) => item.id === alert.patientId); const tone = alert.severity === "Critical" ? colors.error : alert.severity === "Warning" ? colors.warning : colors.primary; return <View key={alert.id} style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.cardTop}><View style={[styles.severityPill, { backgroundColor: `${tone}18` }]}><View style={[styles.dot, { backgroundColor: tone }]} /><Text style={[styles.severityText, { color: tone }]}>{alert.severity}</Text></View><Text style={[styles.time, { color: colors.muted }]}>{alert.createdAt}</Text></View><Text style={[styles.alertTitle, { color: colors.foreground }]}>{alert.title}</Text><Text style={[styles.patient, { color: colors.muted }]}>{patient?.bed} · {patient?.displayCode}</Text><View style={styles.cardBottom}><Text style={[styles.status, { color: colors.muted }]}>{alert.status}</Text><View style={styles.actions}>{alert.status === "Open" && <SmallButton label="Acknowledge" color={colors.primary} onPress={() => confirmAction(alert.id, "acknowledge", "Acknowledge alert?")} />}{alert.status !== "Resolved" && <SmallButton label="Resolve" color={colors.foreground} outline onPress={() => confirmAction(alert.id, "resolve", "Resolve alert?")} />}</View></View></View>})}</View>
    {!visible.length && <View style={styles.empty}><Text style={[styles.emptyTitle, { color: colors.foreground }]}>No alerts in this view</Text><Text style={[styles.emptyText, { color: colors.muted }]}>Try another status filter.</Text></View>}
  </ScrollView></ScreenContainer>;
}
function SmallButton({ label, color, outline, onPress }: { label: string; color: string; outline?: boolean; onPress: () => void }) { const colors = useColors(); return <Pressable onPress={onPress} style={({ pressed }) => [styles.button, { backgroundColor: outline ? "transparent" : color, borderColor: outline ? colors.border : color }, pressed && styles.pressed]}><Text style={{ color: outline ? colors.foreground : "#FFFFFF", fontSize: 11, fontWeight: "800" }}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ content: { paddingTop: 18, paddingBottom: 28 }, eyebrow: { fontSize: 11, fontWeight: "800", letterSpacing: 1.5 }, title: { fontSize: 28, fontWeight: "800", marginTop: 5 }, subtitle: { fontSize: 14, marginTop: 6 }, filters: { gap: 8, paddingVertical: 20 }, filter: { paddingHorizontal: 15, paddingVertical: 9, borderRadius: 20, borderWidth: 1 }, list: { gap: 12 }, card: { borderRadius: 16, borderWidth: 1, padding: 16 }, cardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, severityPill: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 9, paddingVertical: 5, borderRadius: 10 }, dot: { width: 7, height: 7, borderRadius: 4 }, severityText: { fontSize: 11, fontWeight: "800" }, time: { fontSize: 12 }, alertTitle: { fontSize: 15, fontWeight: "800", marginTop: 13 }, patient: { fontSize: 12, marginTop: 5 }, cardBottom: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 15 }, status: { fontSize: 12, fontWeight: "700" }, actions: { flexDirection: "row", gap: 7 }, button: { borderRadius: 9, borderWidth: 1, paddingHorizontal: 9, paddingVertical: 8 }, empty: { alignItems: "center", paddingTop: 55 }, emptyTitle: { fontSize: 16, fontWeight: "800" }, emptyText: { fontSize: 13, marginTop: 6 }, pressed: { opacity: 0.7, transform: [{ scale: 0.98 }] } });
